# Generated by Django 5.2.17 on 2026-09-16 21:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('colors', '0005_color_symbol_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SELF_MANUAL', 'Self-assessed, manually chosen'), ('SELF_TEST', 'Self-assessed, from a test result')], max_length=20, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_assignments', to='colors.colorcombination')),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_color_assignments', to='accounts.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_assignments', to='accounts.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), name='unique_profile_nickname_ci'),
        ),
        migrations.AddConstraint(
            model_name='colorassignment',
            constraint=models.UniqueConstraint(fields=('profile',), name='unique_color_assignment_per_profile'),
        ),
    ]
