# Generated by Django 5.2.17 on 2026-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrationattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='core_feedba_ip_addr_66dff1_idx')],
            },
        ),
    ]
