# Generated by Django 5.2.17 on 2026-09-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dimension',
            field=models.CharField(choices=[('ACTION', 'Action'), ('MOTIVATION', 'Motivation'), ('PERCEPTION', 'Perception')], max_length=20),
        ),
    ]
