# Generated by Django 5.2.17 on 2026-09-17 17:13

import apps.quiz.models
from django.db import migrations, models


def number_existing_answers(apps, schema_editor):
    """Bestehende Antworten (v1) bekommen ihre Position aus der
    Anlage-Reihenfolge — `seed_questionnaire` hat sie in der Reihenfolge
    der Seed-Datei angelegt, die Positionen stimmen also mit der Datei
    überein und ein erneuter Seed-Lauf gegen die veröffentlichte v1
    bleibt unverändert (FR-T6)."""
    AnswerOption = apps.get_model("quiz", "AnswerOption")
    Question = apps.get_model("quiz", "Question")
    for question in Question.objects.all():
        answers = AnswerOption.objects.filter(question=question).order_by("pk")
        for position, answer in enumerate(answers):
            answer.position = position
            answer.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_dimension_action_motivation_perception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['question', 'position']},
        ),
        migrations.AddField(
            model_name='answeroption',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='choice_points',
            field=models.JSONField(default=apps.quiz.models.default_choice_points),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='result_threshold',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.RunPython(number_existing_answers, migrations.RunPython.noop),
    ]
