# Generated by Django 5.2.17 on 2026-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice_points_threshold_answer_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('questionnaire_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('rating__range', (1, 5)), _connector='OR'), name='feedback_rating_between_1_and_5'), models.CheckConstraint(condition=models.Q(('rating__isnull', False), models.Q(('message', ''), _negated=True), _connector='OR'), name='feedback_has_rating_or_message')],
            },
        ),
    ]
