# Generated by Django 5.2.17 on 2026-09-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=100)),
                ('hex', models.CharField(max_length=7)),
                ('wheel_position', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['wheel_position'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('STRENGTH', 'Strength'), ('WEAKNESS', 'Weakness'), ('NEUTRAL', 'Neutral')], max_length=20)),
                ('locale', models.CharField(default='en', max_length=10)),
            ],
            options={
                'ordering': ['locale', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ColorCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('goal', models.TextField(blank=True)),
                ('means', models.TextField(blank=True)),
                ('guiding_question', models.TextField(blank=True)),
                ('archetype', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['locale', 'code'],
                'constraints': [models.UniqueConstraint(fields=('code', 'locale'), name='unique_combination_code_per_locale')],
            },
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_color', models.CharField(blank=True, choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1)),
                ('text', models.TextField()),
                ('locale', models.CharField(default='en', max_length=10)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='colors.colorcombination')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('combination', 'from_color'), name='unique_perspective_per_combination_and_viewpoint')],
            },
        ),
        migrations.CreateModel(
            name='CombinationTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaning_toward', models.CharField(blank=True, choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combination_traits', to='colors.colorcombination')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_combinations', to='colors.trait')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('combination', 'trait'), name='unique_trait_per_combination')],
            },
        ),
    ]
