# Generated by Django 5.2.17 on 2026-09-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_seed_colors_and_combinations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(fields=('name', 'locale'), name='unique_trait_name_per_locale'),
        ),
    ]
