# Generated by Django 5.2.17 on 2026-09-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_trait_unique_trait_name_per_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcombination',
            name='theme',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='PerspectivePole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1)),
                ('term', models.CharField(max_length=40)),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='colors.perspective')),
            ],
            options={
                'ordering': ['perspective', 'color'],
                'constraints': [models.UniqueConstraint(fields=('perspective', 'color'), name='unique_pole_per_perspective_and_color')],
            },
        ),
    ]
