# Generated by Django 5.2.17 on 2026-09-20 20:17

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_colorassignment_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('colors', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^W?U?B?R?G?$', 'Colors must be in WUBRG order, once each.')])),
                ('visibility', models.CharField(choices=[('public', 'Public')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('comment_seq', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['colors', '-created_at'], name='posts_post_colors_c1a025_idx'), models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='post_title_not_empty'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('body'), 10000), name='post_body_max_length'), models.CheckConstraint(condition=models.Q(('colors__regex', '^W?U?B?R?G?$')), name='post_colors_canonical')],
            },
        ),
    ]
