# Generated by Django 5.2.17 on 2026-09-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_colorassignment_test_result'),
        ('posts', '0004_report_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_number', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='posts.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_seen', to='accounts.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'post'), name='post_seen_once_per_person_and_post')],
            },
        ),
    ]
