# Generated by Django 5.2.17 on 2026-09-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_colorassignment_test_result'),
        ('posts', '0005_postseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='posts.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='posts.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='pin_exactly_one_of_post_or_comment'), models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('profile', 'post'), name='pin_once_per_person_and_post'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('profile', 'comment'), name='pin_once_per_person_and_comment')],
            },
        ),
    ]
