# Generated by Django 5.2.17 on 2026-09-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_colorassignment_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_a', to='accounts.profile')),
                ('profile_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_b', to='accounts.profile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='accounts.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile_a', 'profile_b'), name='unique_friendship_pair'), models.CheckConstraint(condition=models.Q(('profile_a__lt', models.F('profile_b'))), name='friendship_pair_ordered_no_self'), models.CheckConstraint(condition=models.Q(('requested_by', models.F('profile_a')), ('requested_by', models.F('profile_b')), _connector='OR'), name='friendship_requested_by_is_a_participant')],
            },
        ),
    ]
